apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - name: container-mysql
      image: mysql:latest
      resources:
        limits:
          cpu: "1"
          memory: "10Mi"
      ports:
        - containerPort: 3306