apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
    - name: container-nginx
      image: nginx:latest
      resources:
        limits:
          cpu: "1"
          memory: "10Mi"
      ports:
        - containerPort: 80